spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    path: "/api-docs"

---
spring:
  config:
    activate.on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

admin:
  username: "1"
  password: "test"

logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate.on-profile: prod

springdoc:
  api-docs:
    enabled: false
