spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    path: "/api-docs"

---
spring:
  config:
    activate.on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

admin:
  username: "1"
  password: "test"

logging:
  level:
    org.hibernate.SQL: debug

jwt:
    secret: 5dc5ef5de6e3094ec5fd308585eeff44950e9d8b87e95044bcbf7ec7200fd968632d73ee605c07df2a9d1f7dd6e5ced6903f9d029f682464079d311daeebb339

---
spring:
  config:
    activate.on-profile: prod

springdoc:
  api-docs:
    enabled: false
